// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: distpebble/v1/seq.proto

package distpebblev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTxnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txn *Txn `protobuf:"bytes,1,opt,name=txn,proto3" json:"txn,omitempty"`
}

func (x *CreateTxnRequest) Reset() {
	*x = CreateTxnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distpebble_v1_seq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTxnRequest) ProtoMessage() {}

func (x *CreateTxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distpebble_v1_seq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTxnRequest.ProtoReflect.Descriptor instead.
func (*CreateTxnRequest) Descriptor() ([]byte, []int) {
	return file_distpebble_v1_seq_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTxnRequest) GetTxn() *Txn {
	if x != nil {
		return x.Txn
	}
	return nil
}

type CreateTxnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateTxnResponse) Reset() {
	*x = CreateTxnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distpebble_v1_seq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTxnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTxnResponse) ProtoMessage() {}

func (x *CreateTxnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distpebble_v1_seq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTxnResponse.ProtoReflect.Descriptor instead.
func (*CreateTxnResponse) Descriptor() ([]byte, []int) {
	return file_distpebble_v1_seq_proto_rawDescGZIP(), []int{1}
}

type GetBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBatchRequest) Reset() {
	*x = GetBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distpebble_v1_seq_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchRequest) ProtoMessage() {}

func (x *GetBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distpebble_v1_seq_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchRequest.ProtoReflect.Descriptor instead.
func (*GetBatchRequest) Descriptor() ([]byte, []int) {
	return file_distpebble_v1_seq_proto_rawDescGZIP(), []int{2}
}

type GetBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txns []*Txn `protobuf:"bytes,1,rep,name=txns,proto3" json:"txns,omitempty"`
}

func (x *GetBatchResponse) Reset() {
	*x = GetBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distpebble_v1_seq_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchResponse) ProtoMessage() {}

func (x *GetBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distpebble_v1_seq_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchResponse.ProtoReflect.Descriptor instead.
func (*GetBatchResponse) Descriptor() ([]byte, []int) {
	return file_distpebble_v1_seq_proto_rawDescGZIP(), []int{3}
}

func (x *GetBatchResponse) GetTxns() []*Txn {
	if x != nil {
		return x.Txns
	}
	return nil
}

// Basic statement
type Get struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key *KeyEntry `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *Get) Reset() {
	*x = Get{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distpebble_v1_seq_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get) ProtoMessage() {}

func (x *Get) ProtoReflect() protoreflect.Message {
	mi := &file_distpebble_v1_seq_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get.ProtoReflect.Descriptor instead.
func (*Get) Descriptor() ([]byte, []int) {
	return file_distpebble_v1_seq_proto_rawDescGZIP(), []int{4}
}

func (x *Get) GetKey() *KeyEntry {
	if x != nil {
		return x.Key
	}
	return nil
}

type Set struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *KeyEntry `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Valie []byte    `protobuf:"bytes,2,opt,name=valie,proto3" json:"valie,omitempty"`
}

func (x *Set) Reset() {
	*x = Set{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distpebble_v1_seq_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Set) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Set) ProtoMessage() {}

func (x *Set) ProtoReflect() protoreflect.Message {
	mi := &file_distpebble_v1_seq_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Set.ProtoReflect.Descriptor instead.
func (*Set) Descriptor() ([]byte, []int) {
	return file_distpebble_v1_seq_proto_rawDescGZIP(), []int{5}
}

func (x *Set) GetKey() *KeyEntry {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Set) GetValie() []byte {
	if x != nil {
		return x.Valie
	}
	return nil
}

type Delete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key *KeyEntry `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *Delete) Reset() {
	*x = Delete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distpebble_v1_seq_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete) ProtoMessage() {}

func (x *Delete) ProtoReflect() protoreflect.Message {
	mi := &file_distpebble_v1_seq_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete.ProtoReflect.Descriptor instead.
func (*Delete) Descriptor() ([]byte, []int) {
	return file_distpebble_v1_seq_proto_rawDescGZIP(), []int{6}
}

func (x *Delete) GetKey() *KeyEntry {
	if x != nil {
		return x.Key
	}
	return nil
}

type Scan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartKey *KeyEntry `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey   *KeyEntry `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
}

func (x *Scan) Reset() {
	*x = Scan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distpebble_v1_seq_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Scan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scan) ProtoMessage() {}

func (x *Scan) ProtoReflect() protoreflect.Message {
	mi := &file_distpebble_v1_seq_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scan.ProtoReflect.Descriptor instead.
func (*Scan) Descriptor() ([]byte, []int) {
	return file_distpebble_v1_seq_proto_rawDescGZIP(), []int{7}
}

func (x *Scan) GetStartKey() *KeyEntry {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *Scan) GetEndKey() *KeyEntry {
	if x != nil {
		return x.EndKey
	}
	return nil
}

// Sequencer
type GetGlobalOrderedTxnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txn *Txn `protobuf:"bytes,1,opt,name=txn,proto3" json:"txn,omitempty"`
}

func (x *GetGlobalOrderedTxnRequest) Reset() {
	*x = GetGlobalOrderedTxnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distpebble_v1_seq_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGlobalOrderedTxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalOrderedTxnRequest) ProtoMessage() {}

func (x *GetGlobalOrderedTxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distpebble_v1_seq_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalOrderedTxnRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalOrderedTxnRequest) Descriptor() ([]byte, []int) {
	return file_distpebble_v1_seq_proto_rawDescGZIP(), []int{8}
}

func (x *GetGlobalOrderedTxnRequest) GetTxn() *Txn {
	if x != nil {
		return x.Txn
	}
	return nil
}

type GetGlobalOrderedTxnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txn *Txn `protobuf:"bytes,1,opt,name=txn,proto3" json:"txn,omitempty"`
}

func (x *GetGlobalOrderedTxnResponse) Reset() {
	*x = GetGlobalOrderedTxnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distpebble_v1_seq_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGlobalOrderedTxnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalOrderedTxnResponse) ProtoMessage() {}

func (x *GetGlobalOrderedTxnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distpebble_v1_seq_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalOrderedTxnResponse.ProtoReflect.Descriptor instead.
func (*GetGlobalOrderedTxnResponse) Descriptor() ([]byte, []int) {
	return file_distpebble_v1_seq_proto_rawDescGZIP(), []int{9}
}

func (x *GetGlobalOrderedTxnResponse) GetTxn() *Txn {
	if x != nil {
		return x.Txn
	}
	return nil
}

var File_distpebble_v1_seq_proto protoreflect.FileDescriptor

var file_distpebble_v1_seq_proto_rawDesc = []byte{
	0x0a, 0x17, 0x64, 0x69, 0x73, 0x74, 0x70, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x64, 0x69, 0x73, 0x74, 0x70,
	0x65, 0x62, 0x62, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x64, 0x69, 0x73, 0x74, 0x70, 0x65,
	0x62, 0x62, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x78, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x38, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x78, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x03, 0x74, 0x78, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x70, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x54, 0x78, 0x6e, 0x52, 0x03, 0x74, 0x78, 0x6e, 0x22, 0x13, 0x0a, 0x11, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x78, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x70, 0x65, 0x62, 0x62,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x78, 0x6e, 0x52, 0x04, 0x74, 0x78, 0x6e, 0x73, 0x22,
	0x30, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x29, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x70, 0x65, 0x62, 0x62, 0x6c, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x46, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x29, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x70, 0x65, 0x62, 0x62,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x65, 0x22, 0x33, 0x0a, 0x06, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x12, 0x29, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x70, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x6e,
	0x0a, 0x04, 0x53, 0x63, 0x61, 0x6e, 0x12, 0x34, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x69, 0x73, 0x74,
	0x70, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x30, 0x0a, 0x07,
	0x65, 0x6e, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x64, 0x69, 0x73, 0x74, 0x70, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65,
	0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x22, 0x42,
	0x0a, 0x1a, 0x47, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x65, 0x64, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x03,
	0x74, 0x78, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x69, 0x73, 0x74,
	0x70, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x78, 0x6e, 0x52, 0x03, 0x74,
	0x78, 0x6e, 0x22, 0x43, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x65, 0x64, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x24, 0x0a, 0x03, 0x74, 0x78, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x64, 0x69, 0x73, 0x74, 0x70, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x78, 0x6e, 0x52, 0x03, 0x74, 0x78, 0x6e, 0x32, 0xb3, 0x01, 0x0a, 0x10, 0x53, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x09,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x78, 0x6e, 0x12, 0x1f, 0x2e, 0x64, 0x69, 0x73, 0x74,
	0x70, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x78, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x64, 0x69, 0x73,
	0x74, 0x70, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1e, 0x2e, 0x64, 0x69, 0x73,
	0x74, 0x70, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x64, 0x69, 0x73,
	0x74, 0x70, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0xb7, 0x01,
	0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x70, 0x65, 0x62, 0x62, 0x6c, 0x65,
	0x2e, 0x76, 0x31, 0x42, 0x08, 0x53, 0x65, 0x71, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x63, 0x68,
	0x75, 0x6e, 0x77, 0x75, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x70, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x70, 0x65,
	0x62, 0x62, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x64, 0x69, 0x73, 0x74, 0x70, 0x65, 0x62, 0x62,
	0x6c, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x44, 0x58, 0x58, 0xaa, 0x02, 0x0d, 0x44, 0x69, 0x73,
	0x74, 0x70, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0d, 0x44, 0x69, 0x73,
	0x74, 0x70, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x19, 0x44, 0x69, 0x73,
	0x74, 0x70, 0x65, 0x62, 0x62, 0x6c, 0x65, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0e, 0x44, 0x69, 0x73, 0x74, 0x70, 0x65, 0x62,
	0x62, 0x6c, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_distpebble_v1_seq_proto_rawDescOnce sync.Once
	file_distpebble_v1_seq_proto_rawDescData = file_distpebble_v1_seq_proto_rawDesc
)

func file_distpebble_v1_seq_proto_rawDescGZIP() []byte {
	file_distpebble_v1_seq_proto_rawDescOnce.Do(func() {
		file_distpebble_v1_seq_proto_rawDescData = protoimpl.X.CompressGZIP(file_distpebble_v1_seq_proto_rawDescData)
	})
	return file_distpebble_v1_seq_proto_rawDescData
}

var file_distpebble_v1_seq_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_distpebble_v1_seq_proto_goTypes = []interface{}{
	(*CreateTxnRequest)(nil),            // 0: distpebble.v1.CreateTxnRequest
	(*CreateTxnResponse)(nil),           // 1: distpebble.v1.CreateTxnResponse
	(*GetBatchRequest)(nil),             // 2: distpebble.v1.GetBatchRequest
	(*GetBatchResponse)(nil),            // 3: distpebble.v1.GetBatchResponse
	(*Get)(nil),                         // 4: distpebble.v1.Get
	(*Set)(nil),                         // 5: distpebble.v1.Set
	(*Delete)(nil),                      // 6: distpebble.v1.Delete
	(*Scan)(nil),                        // 7: distpebble.v1.Scan
	(*GetGlobalOrderedTxnRequest)(nil),  // 8: distpebble.v1.GetGlobalOrderedTxnRequest
	(*GetGlobalOrderedTxnResponse)(nil), // 9: distpebble.v1.GetGlobalOrderedTxnResponse
	(*Txn)(nil),                         // 10: distpebble.v1.Txn
	(*KeyEntry)(nil),                    // 11: distpebble.v1.KeyEntry
}
var file_distpebble_v1_seq_proto_depIdxs = []int32{
	10, // 0: distpebble.v1.CreateTxnRequest.txn:type_name -> distpebble.v1.Txn
	10, // 1: distpebble.v1.GetBatchResponse.txns:type_name -> distpebble.v1.Txn
	11, // 2: distpebble.v1.Get.key:type_name -> distpebble.v1.KeyEntry
	11, // 3: distpebble.v1.Set.key:type_name -> distpebble.v1.KeyEntry
	11, // 4: distpebble.v1.Delete.key:type_name -> distpebble.v1.KeyEntry
	11, // 5: distpebble.v1.Scan.start_key:type_name -> distpebble.v1.KeyEntry
	11, // 6: distpebble.v1.Scan.end_key:type_name -> distpebble.v1.KeyEntry
	10, // 7: distpebble.v1.GetGlobalOrderedTxnRequest.txn:type_name -> distpebble.v1.Txn
	10, // 8: distpebble.v1.GetGlobalOrderedTxnResponse.txn:type_name -> distpebble.v1.Txn
	0,  // 9: distpebble.v1.SequencerService.CreateTxn:input_type -> distpebble.v1.CreateTxnRequest
	2,  // 10: distpebble.v1.SequencerService.GetBatch:input_type -> distpebble.v1.GetBatchRequest
	1,  // 11: distpebble.v1.SequencerService.CreateTxn:output_type -> distpebble.v1.CreateTxnResponse
	3,  // 12: distpebble.v1.SequencerService.GetBatch:output_type -> distpebble.v1.GetBatchResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_distpebble_v1_seq_proto_init() }
func file_distpebble_v1_seq_proto_init() {
	if File_distpebble_v1_seq_proto != nil {
		return
	}
	file_distpebble_v1_txn_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_distpebble_v1_seq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTxnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distpebble_v1_seq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTxnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distpebble_v1_seq_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distpebble_v1_seq_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distpebble_v1_seq_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Get); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distpebble_v1_seq_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Set); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distpebble_v1_seq_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distpebble_v1_seq_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Scan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distpebble_v1_seq_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGlobalOrderedTxnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distpebble_v1_seq_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGlobalOrderedTxnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_distpebble_v1_seq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_distpebble_v1_seq_proto_goTypes,
		DependencyIndexes: file_distpebble_v1_seq_proto_depIdxs,
		MessageInfos:      file_distpebble_v1_seq_proto_msgTypes,
	}.Build()
	File_distpebble_v1_seq_proto = out.File
	file_distpebble_v1_seq_proto_rawDesc = nil
	file_distpebble_v1_seq_proto_goTypes = nil
	file_distpebble_v1_seq_proto_depIdxs = nil
}
